### ISSUE TITLE
to-do list for darrell v1.0.0

### ISSUE THREAD

**Issue by epsimatt** [epsimatt/darrell#1]
darrell v1.0.0

- [ ] 메뉴 바 구현하기
- [ ] 텍스트 박스 구현하기
- [ ] 사용자가 입력한 텍스트의 색깔을 변경하는 기능 구현하기
- [ ] 사용자가 입력한 키를 보여주는 기능 구현하기
